# Generated by Django 5.2 on 2025-04-12 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptionmedication',
            name='afternoon',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prescriptionmedication',
            name='evening',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prescriptionmedication',
            name='morning',
            field=models.BooleanField(default=False),
        ),
    ]
