# Generated by Django 5.2 on 2025-04-13 06:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0002_prescriptionmedication_afternoon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptionmedication',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
