# Generated by Django 5.2 on 2025-04-15 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0004_medicationadherence'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptionmedication',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
