# Generated by Django 5.2 on 2025-04-15 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0005_prescriptionmedication_is_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescriptionmedication',
            name='is_completed',
        ),
        migrations.AlterField(
            model_name='prescriptionmedication',
            name='duration',
            field=models.IntegerField(default=1, max_length=100),
        ),
    ]
