# Generated by Django 5.2 on 2025-04-15 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0006_remove_prescriptionmedication_is_completed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescriptionmedication',
            name='duration',
            field=models.IntegerField(default=1),
        ),
    ]
