# Generated by Django 5.2 on 2025-04-15 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0007_alter_prescriptionmedication_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescriptionmedication',
            name='duration',
            field=models.CharField(max_length=100),
        ),
    ]
