# Generated by Django 5.2 on 2025-04-11 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='caregiver',
            name='liscense_no',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='business_no',
            field=models.CharField(default='', max_length=15),
        ),
    ]
