# Generated by Django 5.2 on 2025-04-13 07:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_symptom', models.CharField(max_length=255)),
                ('duration', models.CharField(help_text='e.g., 2 days, 1 week', max_length=100)),
                ('severity', models.CharField(choices=[('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe')], max_length=50)),
                ('allergies', models.TextField(blank=True, help_text='Any known allergies')),
                ('travel_history', models.TextField(blank=True, help_text='Recent travel history if any')),
                ('additional_description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
