# Generated by Django 5.2 on 2025-04-11 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_caregiver_liscense_no_pharmacy_business_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('doctor', 'Doctor'), ('patient', 'Patient'), ('caregiver', 'Caregiver'), ('pharmacy', 'Pharmacy')], default='tenant', max_length=10),
        ),
    ]
