# Generated by Django 5.2 on 2025-04-14 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('doctor', 'Doctor'), ('patient', 'Patient'), ('caregiver', 'Caregiver'), ('pharmacy', 'Pharmacy')], default='patient', max_length=10),
        ),
    ]
