# Generated by Django 5.2 on 2025-04-15 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
